### ISSUE TITLE
Performance testing - How did you disable cache and which web browser did you use for testing?

### ISSUE THREAD

**Issue by iwis** [coding-flamingo/BlazorComponents#2]
You have said [here](https://youtu.be/Lp5mj3lWxu8?t=179): "I disabled cache and I refresh the page". I have two questions:

1. If you used Google Chrome, then did you disable cache using the "Disable cache" checkbox in Developer tools (F12) > Network?

2. Did you also delete DLL libraries stored in Developer tools (F12) > Application > Cache > Cache Storage, by selecting the "Delete" command available after clicking the right mouse button?

**Comment by igalfsg** [comment]
I Did both
